// ═══════════════════════════════════════════════════════════════════════════
// derive.js — the data join at the heart of the VM-as-subject re-model.
//
// /api/state is FLAT: virtual_machines is one array, and every network/firewall
// row a VM owns lives in a *separate* anonymous array (routes, nft rules,
// neigh_proxy, ip_rules, reserved_ips, units, snapshots). The flat document
// "can't join a VM to its own rows." These pure functions do that join, so the
// VM can become the subject.
//
// PURE. No Vue, no DOM, no fetch — every function takes plain data and returns
// plain data, so it's unit-testable and reasoned about in isolation.
//
// DEFENSIVE by design (mirroring the backend's "server is a
// cache" philosophy): a missing field yields a dropped leg or a "—" cell, never
// a thrown error. The matchers key off whatever identifying tokens a VM row
// happens to carry, so they work across all three fixtures, which now share ONE
// shape (backend/server.py's build_state()) and differ only in CARDINALITY:
//   · mock/state-ordinary.json (~24 VMs) + state-scale.json (~1000 VMs) —
//     generated by mock/generate.mjs.
//   · mock/state-real.json — a live `server.py --collect` capture off a real
//     host (mock/collect-real.mjs), so nothing is idealised.
// All three carry the real host shape: nft keyed on host_veth `atlas-h<...>`
// plus IPv6 daddr/saddr, NAT written `dnat ip to X` / `snat ip to X`, reserved
// rows carry guest_ipv4, anchor is null (Scaleway, no DO anchor).
// ═══════════════════════════════════════════════════════════════════════════

const EMPTY = "—";

function uuid8(uuid) {
	return uuid ? String(uuid).slice(0, 8) : "";
}

// The set of strings that identify a VM's rows in the flat document. A row
// belongs to the VM if it mentions ANY of these. Ordered roughly host-veth →
// guest addrs; all are distinctive enough not to collide across VMs.
function vmTokens(vm) {
	const t = [];
	const push = (v) => {
		if (v != null && v !== "") t.push(String(v));
	};
	push(vm.host_veth); // real hosts: atlas-h<uuid7>
	push(vm.namespace_veth); // real hosts: atlas-n<uuid7>
	if (vm.uuid) push(`veth-${uuid8(vm.uuid)}`); // mock/scale convention
	push(vm.ipv4_guest);
	push(vm.ipv6);
	push(vm.tap_device);
	push(vm.netns);
	push(vm.reserved_ipv4);
	return t;
}

// Does `hay` (a rule string, a route dev/dest, an NDP address, …) reference any
// of the VM's tokens? Substring match — nft rules and routes embed these verbatim.
function mentions(hay, tokens) {
	if (hay == null) return false;
	const s = String(hay);
	return tokens.some((tok) => s.includes(tok));
}

// Flatten nft into {family, table, persisted, chain, type, rule} records once,
// so every matcher and the reverse index share one view of the ruleset.
function nftRecords(state) {
	const out = [];
	for (const t of state.nft_tables || []) {
		for (const c of t.chains || []) {
			for (const rule of c.rules || []) {
				out.push({
					family: t.family,
					table: t.name,
					persisted: !!t.persisted,
					chain: c.name,
					type: c.type,
					rule,
				});
			}
		}
	}
	return out;
}

// ── deriveVm(state, vm) → the joined detail object ──────────────────────────
// Best-effort: every field defaults to empty/absent rather than throwing.
export function deriveVm(state, vm) {
	const tokens = vmTokens(vm);
	const nft = nftRecords(state);
	const guest = vm.ipv4_guest;

	const routes = (state.routes || []).filter(
		(r) => mentions(r.dev, tokens) || mentions(r.dest, tokens)
	);

	// forward-chain (filter) rules that name this VM (via veth or guest v4/v6).
	const filterRules = nft
		.filter((n) => n.type === "filter" && mentions(n.rule, tokens))
		.map((n) => n.rule);

	// DNAT: a prerouting/nat rule whose TARGET is this guest's v4. Real writes
	// "dnat ip to 100.64.0.14"; mock writes "dnat to 100.64.0.14" — both contain
	// "dnat" and the guest address.
	const dnat =
		guest &&
		nft.find((n) => n.type === "nat" && /\bdnat\b/.test(n.rule) && n.rule.includes(guest))
			?.rule;

	// SNAT: a postrouting/nat rule whose SOURCE is this guest's v4.
	const snat =
		guest &&
		nft.find((n) => n.type === "nat" && /\bsnat\b/.test(n.rule) && n.rule.includes(guest))
			?.rule;

	const ndp = (state.neigh_proxy || []).find((p) => p.address === vm.ipv6) || null;
	const ipRule = (state.ip_rules || []).find((r) => r.from === guest) || null;
	const reserved = (state.reserved_ips || []).find((r) => r.attached_vm === vm.uuid) || null;
	const unit = (state.units || []).find((u) => vm.uuid && u.name.includes(vm.uuid)) || null;
	const snapshot = (state.snapshots || []).find((s) => s.uuid === vm.uuid) || null;

	return {
		vm,
		running: vm.state === "Running",
		tokens,
		routes,
		filterRules,
		dnat: dnat || null,
		snat: snat || null,
		ndp,
		ipRule,
		reserved,
		unit,
		snapshot,
		// Disk lineage. Prefer the LV origin when the backend joins
		// it; otherwise fall back to the (usually null) image name.
		diskOrigin: diskOrigin(vm),
		dataPercent: vm.disk_data_percent != null ? vm.disk_data_percent : null,
		// Per-VM size (vcpus/mem from firecracker.json).
		size: vmSize(vm),
	};
}

// "image ubuntu-24.04" / "snap mjmdd1p7fb" / "—". Mirrors App.vue's diskOrigin.
export function diskOrigin(vm) {
	if (vm.disk_origin) {
		// The column is titled "Image", so a base image shows the bare name; a
		// snapshot origin keeps its "snap " prefix since that's a distinct origin.
		const snap = vm.disk_origin.includes("-snap-");
		const name = vm.disk_origin.replace(/^atlas-(image|snap)-/, "");
		return snap ? `snap ${name}` : name;
	}
	return vm.image || EMPTY;
}

// "1 · 1024m" or "—". Mirrors App.vue's vmSize.
export function vmSize(vm) {
	if (vm.vcpus == null && vm.mem_mib == null) return EMPTY;
	return `${vm.vcpus ?? "?"} · ${vm.mem_mib ?? "?"}m`;
}

// ── Disk rows ───────────────────────────────────────────────────────────────
// A disk row belongs to a VM when it's a device-mapper / LVM volume backing a
// VM's root or a snapshot of one. lsblk dumps EVERY block device — on a busy
// host that's hundreds of per-VM LVs (`atlas-atlas--vm--<uuid>`, `…--snap--…`,
// plus dm `atlas-vm-<uuid>-clone`) that swamp the host-primitive disks the
// operator actually reasons about (the NVMe drives, the RAID md's, partitions,
// the thin pool's own meta/data). This flags the per-VM rows so the Disks view
// can fold them behind a toggle, exactly like Units/Processes fold VM units.
// Base images (`…--image--…`) and pool plumbing stay visible: they're host
// storage, not one VM's disk.
export function diskIsVmRow(disk) {
	const name = disk?.name || "";
	if (disk?.kind !== "lvm" && disk?.kind !== "dm") return false;
	if (name.includes("pool")) return false; // thin-pool meta/data = host plumbing
	if (name.includes("image")) return false; // base images = shared host storage
	// lsblk's dm names double every dash (LV `atlas-vm-x` → `atlas-atlas--vm--x`),
	// so match on the un-doubled token: a vm or snap volume.
	return name.includes("vm") || name.includes("snap");
}

// ── derivePath(detail) → the directed connectivity legs ─────────────────────
// Returns an ordered list of legs, or null for a stopped VM (whose live network
// rows are genuinely torn down — see the "Stopped" note in §4). Each leg is
// { dir, from, hop?, to, xf, key? } where `key:true` marks the darkest-ink node
// (the public reserved IP) and `xf` is the transform tag.
export function derivePath(detail) {
	if (!detail || !detail.running) return null;
	const { vm, reserved } = detail;
	const legs = [];

	// In v6 — always present for a running VM. Routed /128, no NAT.
	if (vm.ipv6) {
		legs.push({ dir: "In v6", from: vm.ipv6, to: "guest", xf: "routed /128" });
	}

	const reservedAddr = reserved?.address || vm.reserved_ipv4 || null;

	if (reservedAddr) {
		// In v4 — DNAT. DO model hops through the anchor; Scaleway is direct
		// (anchor null on Scaleway), so the hop is simply omitted.
		const inLeg = {
			dir: "In v4",
			from: reservedAddr,
			key: true,
			to: vm.ipv4_guest || "guest",
			xf: "DNAT",
		};
		if (reserved?.anchor) inLeg.hop = reserved.anchor;
		legs.push(inLeg);

		// Out v4 — SNAT back to the reserved public IP.
		legs.push({
			dir: "Out v4",
			from: vm.ipv4_guest || "guest",
			to: reservedAddr,
			key: true,
			xf: "SNAT",
		});
	} else if (vm.ipv4_guest) {
		// No reserved IP: outbound v4 is masqueraded behind the uplink.
		const uplink = detail.uplink || "eth0";
		legs.push({
			dir: "Out v4",
			from: vm.ipv4_guest,
			to: uplink,
			xf: "masquerade",
		});
	}

	return legs;
}

// A single prose sentence summarising the VM's forward-chain policy, e.g.
// "veth allowed both ways · 100.64.0.14 accepted · metadata 169.254.169.254 blocked".
// Best-effort readout of the filter rules the join found, plus the host-wide
// metadata drop (which protects every VM, so it's worth stating per-VM).
export function deriveFilterSentence(state, detail) {
	if (!detail || !detail.running) return "";
	const rules = detail.filterRules || [];
	const parts = [];

	const hasIn = rules.some((r) => /iifname|saddr/.test(r) && /\baccept\b/.test(r));
	const hasOut = rules.some((r) => /oifname|daddr/.test(r) && /\baccept\b/.test(r));
	if (hasIn && hasOut) parts.push("veth allowed both ways");
	else if (hasIn) parts.push("inbound allowed");
	else if (hasOut) parts.push("outbound allowed");

	if (detail.vm.ipv4_guest && rules.some((r) => r.includes(detail.vm.ipv4_guest))) {
		parts.push(`${detail.vm.ipv4_guest} accepted`);
	}

	// The metadata drop is a host-wide forward rule; surface it as the protection
	// it is. Detect it once from the ruleset.
	const meta = nftRecords(state).find(
		(n) => n.type === "filter" && /169\.254\.169\.254/.test(n.rule) && /\bdrop\b/.test(n.rule)
	);
	if (meta) parts.push("metadata 169.254.169.254 blocked");

	return parts.join(" · ");
}

// The one sentence a stopped VM's detail shows in place of a path.
export const STOPPED_SENTENCE =
	"Stopped — veth, routes, NAT and firewall rules are torn down. Disk LV persists.";

// ── vmByRule(state) → reverse index ─────────────────────────────────────────
// Given the flat rows, returns lookups that map a row back to its owning VM
// uuid (or null for host fabric). Same matching logic as deriveVm, inverted, so
// the Firewall / Network sections can render a "→ <uuid8>" back-link.
export function vmByRule(state) {
	const vms = state.virtual_machines || [];
	const indexed = vms.map((vm) => ({ vm, tokens: vmTokens(vm) }));

	const owner = (hay) => {
		if (hay == null) return null;
		const s = String(hay);
		for (const { vm, tokens } of indexed) {
			if (tokens.some((tok) => s.includes(tok))) return vm.uuid;
		}
		return null;
	};

	return {
		// nft rule string → uuid|null
		rule: (rule) => owner(rule),
		// route row → uuid|null (match on dev or dest)
		route: (r) => owner(r?.dev) || owner(r?.dest),
		// ndp row → uuid|null
		ndp: (p) => {
			const vm = vms.find((v) => v.ipv6 === p?.address);
			return vm ? vm.uuid : null;
		},
		// ip-rule row → uuid|null
		ipRule: (r) => {
			const vm = vms.find((v) => v.ipv4_guest === r?.from);
			return vm ? vm.uuid : null;
		},
		// reserved-ip row → uuid|null (it already carries attached_vm)
		reserved: (r) => r?.attached_vm || null,
		// unit row → uuid|null (firecracker-vm@<uuid>.service)
		unit: (u) => {
			const vm = vms.find((v) => v.uuid && u?.name?.includes(v.uuid));
			return vm ? vm.uuid : null;
		},
		// generic: any string
		any: owner,
	};
}

// ── hostResidue(state) → the rows NOT claimed by any VM ──────────────────────
// Whatever no VM owns is "host fabric": default routes, the masquerade-all rule,
// the metadata-drop rule, the mgmt-input chain, atlas-pool.service, nftables.
// service, migrate-forwarder units, the uplink interface, etc. The section
// tables render these plain (no back-link). Returns unclaimed rows per section.
export function hostResidue(state) {
	const idx = vmByRule(state);
	return {
		routes: (state.routes || []).filter((r) => !idx.route(r)),
		neigh_proxy: (state.neigh_proxy || []).filter((p) => !idx.ndp(p)),
		ip_rules: (state.ip_rules || []).filter((r) => !idx.ipRule(r)),
		nftRules: nftRecords(state).filter((n) => !idx.rule(n.rule)),
		units: (state.units || []).filter((u) => u.kind !== "vm" && !idx.unit(u)),
	};
}

// ═══════════════════════════════════════════════════════════════════════════
// The scale/status layer (the Overview domain). Everything below is still PURE
// and DEFENSIVE, and — crucially — HONEST: the page is static (read-once,
// refresh to update), so nothing here invents liveness. Every alert traces to a
// true fact in THIS snapshot; a fact we can't read yields no alert, never a
// faked one. There is no server-side alert history yet, so `cleared` is empty
// by construction (not fabricated) until the backend carries it.
// ═══════════════════════════════════════════════════════════════════════════

// ── per-VM facets (Plan A) — the 3 per-VM features double as Machines columns ──
// A VM files each feature in its domain AND shows here, so the table and the
// domain cross-link. All best-effort: absent → false/null, never a throw.

// Ingress: does a public path terminate at this VM? True if it holds a reserved
// public v4 OR a proxy map publishes to it. Returns a short label for the column.
export function vmIngress(state, vm) {
	if (vm.reserved_ipv4) return { kind: "reserved", label: vm.reserved_ipv4 };
	const map = (state.proxy_maps || []).find((m) => m.vm === vm.uuid);
	if (map) return { kind: "proxy", label: map.sni || map.listen || "proxy" };
	return null;
}

// Migrating: is this VM in flight? The row flag is authoritative; fall back to a
// live migration row whose unit carries the VM's short uuid.
export function vmMigrating(state, vm) {
	if (vm.migrating) return true;
	const u8 = uuid8(vm.uuid);
	return (state.migrations || []).some(
		(m) => m.state === "running" && u8 && String(m.unit || "").includes(u8)
	);
}

// ── sizeDistribution(state, resource) → the running-VM size histogram ────────
// At scale "what's on this host" is a SHAPE, not a list. Real hosts run VMs of
// ARBITRARY sizes, not just the tidy classes — so we bin by power-of-two RANGES
// (≤1G, 1–2G, 2–4G, …) rather than by exact size. Any size lands in a sensible
// range, and the chart stays a fixed handful of bars instead of sprouting a thin
// column per distinct value. Empty ranges between the min and max present size
// are kept so the shape reads continuously; ranges outside that span are dropped.
//
// `resource` picks which measure the VMs are binned BY and what the bar length
// SUMS: "mem" (default), "cpu", or "disk". A bin's `weight` is the total resource
// in that range — so the fullest range by load reads longest — while `count` is
// how many VMs fall there. Returns { buckets:[{label, lo, count, weight}], max,
// total, unit } where `max` is over weight (the bar scale) and `total` is the VM
// count.
const SIZE_RESOURCES = {
	// Edges are in the same unit as `value` returns, so binning is a direct compare.
	// mem in GiB (mem_mib→GiB up front) keeps every resource's edges in display units.
	mem: {
		unit: "G",
		edges: [0, 1, 2, 4, 8, 16, 32],
		value: (v) => (v.mem_mib || 0) / 1024,
		weight: (v) => (v.mem_mib || 0) / 1024,
	},
	cpu: {
		unit: "vCPU",
		edges: [0, 1, 2, 4, 8, 16, 32],
		value: (v) => v.vcpus || 0,
		weight: (v) => v.vcpus || 0,
	},
	disk: {
		unit: "G",
		edges: [0, 16, 32, 64, 128, 256, 512],
		value: (v) => (v.disk_size_bytes || 0) / 1073741824,
		weight: (v) => (v.disk_size_bytes || 0) / 1073741824,
	},
};

export function sizeDistribution(state, resource = "mem") {
	const R = SIZE_RESOURCES[resource] || SIZE_RESOURCES.mem;
	const running = (state.virtual_machines || []).filter((v) => v.state === "Running");
	const counts = new Array(R.edges.length).fill(0);
	const weights = new Array(R.edges.length).fill(0);
	for (const vm of running) {
		const m = R.value(vm);
		let bin = 0;
		for (let i = 0; i < R.edges.length; i++) if (m >= R.edges[i]) bin = i;
		counts[bin] += 1;
		weights[bin] += R.weight(vm);
	}
	// Trim to the occupied span so we don't show a run of leading/trailing zeros,
	// but keep interior zero ranges (a real gap in the fleet shape).
	let first = counts.findIndex((c) => c > 0);
	let last = counts.length - 1;
	while (last > first && counts[last] === 0) last -= 1;
	if (first < 0) return { buckets: [], max: 0, total: 0, unit: R.unit };
	const buckets = [];
	for (let i = first; i <= last; i++) {
		buckets.push({
			lo: R.edges[i],
			label: rangeLabel(R.edges[i], R.edges[i + 1], R.unit),
			count: counts[i],
			weight: weights[i],
		});
	}
	const max = buckets.reduce((m, b) => Math.max(m, b.weight), 0);
	return { buckets, max, total: running.length, unit: R.unit };
}

// "≤1G" / "1–2G" / "2–4G" / "≥32G" — a range label from a bin's [lo, hi) edges.
// vCPU bins are plain integers (no G suffix); GiB bins carry a "G".
function rangeLabel(lo, hi, unit) {
	if (unit === "vCPU") {
		if (lo === 0) return `≤${hi}`;
		if (hi === undefined) return `≥${lo}`;
		return `${lo}–${hi}`;
	}
	const g = (n) => (n % 1 ? n.toFixed(1) : String(n));
	if (lo === 0) return `≤${g(hi)}G`;
	if (hi === undefined) return `≥${g(lo)}G`;
	return `${g(lo)}–${g(hi)}G`;
}

// ── metrics(state) → the host time-series, shaped for charts ─────────────────
// The backend emits `metrics.series` as { key: { unit, points[] } }. This maps
// the raw series into an ordered, labelled list the Analytics/Overview charts
// render. Best-effort: no metrics key → empty list, and the caller shows the
// honest "no history yet" note. Each entry: { key, label, unit, points, format }.
const METRIC_ORDER = [
	{ key: "cpu_util_pct", label: "CPU utilisation", unit: "%", fmt: (v) => `${Math.round(v)}%` },
	{ key: "mem_used_mib", label: "Memory used", unit: "MiB", fmt: (v) => fmtMib(v) },
	{
		key: "disk_io_iops",
		label: "Disk IO",
		unit: "iops",
		fmt: (v) => `${Math.round(v).toLocaleString("en-US")} iops`,
	},
	{ key: "pool_used_pct", label: "Pool used", unit: "%", fmt: (v) => `${v.toFixed(1)}%` },
	{
		key: "net_rx_mbps",
		label: "Network in",
		unit: "Mb/s",
		fmt: (v) => `${Math.round(v).toLocaleString("en-US")} Mb/s`,
	},
	{
		key: "net_tx_mbps",
		label: "Network out",
		unit: "Mb/s",
		fmt: (v) => `${Math.round(v).toLocaleString("en-US")} Mb/s`,
	},
];

export function metrics(state) {
	const series = state.metrics?.series || {};
	const out = [];
	for (const m of METRIC_ORDER) {
		const s = series[m.key];
		if (!s || !Array.isArray(s.points) || !s.points.length) continue;
		out.push({
			key: m.key,
			label: m.label,
			unit: s.unit || m.unit,
			points: s.points,
			format: m.fmt,
		});
	}
	return out;
}

// The full ordered metric list with EMPTY points — the chart skeleton the
// Analytics view renders when the host carries no history yet. Same panels, same
// labels, same layout; the charts just draw their empty frame (an honest "no
// history" state) instead of a fabricated trend. Keeps the design intact rather
// than collapsing metrics to prose.
export function metricSkeleton() {
	return METRIC_ORDER.map((m) => ({
		key: m.key,
		label: m.label,
		unit: m.unit,
		points: [],
		format: m.fmt,
	}));
}

export function hasMetrics(state) {
	return metrics(state).length > 0;
}

// One unit family across the whole dashboard (the g/G mix the user flagged): G,
// with T above 1024G and M below 1G. Bare suffix, no "iB".
function fmtMib(mib) {
	if (mib >= 1024 * 1024) return `${(mib / 1024 / 1024).toFixed(1)}T`;
	if (mib >= 1024) return `${(mib / 1024).toFixed(1)}G`;
	return `${Math.round(mib)}M`;
}

// ── quotas(state) → the pressure bars ────────────────────────────────────────
// Committed vCPU / RAM / pool-disk vs the host's over-provision BUDGET
// (physical × factor). Each bar carries: used (running), reserved-idle (held by
// stopped/paused VMs — reclaimable), the budget, the physical line, and a
// severity band. Honest denominators: if the backend didn't emit host totals,
// the bar reports committed-only with `budget: null` and no false headroom.
export function quotas(state) {
	const host = state.host || {};
	const vms = state.virtual_machines || [];
	const factor = host.overprovision_factor || 1;

	const live = (v) => v.state === "Running";
	const idle = (v) => v.state === "Stopped" || v.state === "Paused";

	const sum = (pred, field) => vms.reduce((n, v) => n + (pred(v) ? v[field] || 0 : 0), 0);

	const cpuBudget = host.cpu_total != null ? host.cpu_total * factor : null;
	const memBudget = host.mem_total_mib != null ? host.mem_total_mib * factor : null;

	const pool = state.pool || {};
	const poolPct = pool.data_percent != null ? pool.data_percent : null;

	return [
		bar("vCPU", sum(live, "vcpus"), sum(idle, "vcpus"), cpuBudget, host.cpu_total, ""),
		bar(
			"Memory",
			sum(live, "mem_mib"),
			sum(idle, "mem_mib"),
			memBudget,
			host.mem_total_mib,
			"MiB"
		),
		poolBar(poolPct, pool.size),
	];
}

// One quota bar. `used` = committed by running VMs; `idle` = held by
// stopped/paused (reclaimable); denominator = the over-provision budget.
function bar(label, used, idle, budget, physical, unit) {
	const pct = budget ? (used + idle) / budget : null;
	return {
		label,
		used,
		idle,
		budget,
		physical,
		unit,
		fraction: pct, // committed / budget, or null when no budget known
		severity: sev(pct),
	};
}

// The pool bar reads its fill straight from lvs (already a %), so it's framed
// against 100% of the pool, not the vCPU/RAM over-provision budget. We also
// resolve absolute GiB (used / total) from the lvs `size` string so the headline
// can show real capacity, not just a bare %. If `percent` is missing/odd the bar
// fails to EMPTY (fraction null → 0-width), never to full.
function poolBar(percent, size) {
	const frac = percent != null ? percent / 100 : null;
	const totalGib = parseLvSize(size);
	const usedGib = totalGib != null && frac != null ? totalGib * frac : null;
	return {
		label: "Pool",
		used: percent,
		idle: 0,
		budget: percent != null ? 100 : null,
		physical: null,
		unit: "%",
		size: size || null,
		usedGib,
		totalGib,
		fraction: frac,
		severity: sev(frac),
	};
}

// Parse an lvs size string ("686.16g", "2.00t", "80.00g") to GiB. lvs reports
// GiB/TiB (binary) with a lowercase suffix; unknown shapes → null so the bar
// degrades to a bare % rather than inventing a number. lvs also prefixes a
// rounded value with "<"/"~" ("<886.24g") — tolerate and drop it.
function parseLvSize(size) {
	if (!size) return null;
	const m = String(size)
		.trim()
		.replace(/^[<~]/, "")
		.match(/^([\d.]+)\s*([kmgtp])?i?b?$/i);
	if (!m) return null;
	const n = parseFloat(m[1]);
	if (!Number.isFinite(n)) return null;
	const mult = { k: 1 / 1024 / 1024, m: 1 / 1024, g: 1, t: 1024, p: 1024 * 1024 };
	return n * (mult[(m[2] || "g").toLowerCase()] ?? 1);
}

// ── Bytes → a compact binary size in the SAME unit family as everywhere else
// (G, with T above 1024G). One `trim`-ed number + a bare "G"/"T" — so volumes,
// disks, the pool and the provisioning panel all read in one unit (the g/G mix
// the user flagged). null bytes → "".
export function fmtGiB(bytes) {
	if (bytes == null || !Number.isFinite(bytes)) return "";
	const g = bytes / GIB;
	if (g >= 1024) return `${trim(g / 1024)}T`;
	return `${trim(g)}G`;
}

// Normalise a raw LVM size string (the vendor emits "4.00g", "28.00g") into the
// dashboard's one unit family: an uppercase suffix (G/T/M/K) so images, snapshots
// and every other raw-size column read the same "G" as fmtGiB. Leaves anything
// unrecognised (already-formatted, empty) untouched.
export function fmtSize(value) {
	if (value == null || value === "") return "";
	return String(value).replace(/([kmgtpe])(ib)?$/i, (m, u) => u.toUpperCase());
}

// A data-fill percentage → rounded "N%". The single rounding rule so every list
// that shows a data_percent (snapshots, volumes, VM disk) reads it identically.
export function pct(value) {
	return value == null || value === "" ? "" : `${Math.round(value)}%`;
}

// ── storage(state) → the LVM stack, summarised. Physical PV → VG → thin pool,
// each as used/total in one unit, plus the pool fill %. Drives the Storage summary
// strip that sits above the volumes list (item 16-A). Everything reads from the
// `_bytes` fields so units are consistent; the lvs `size` strings are ignored for
// display. Degrades to null members on a sparse host (honest blanks).
export function storage(state) {
	const st = state.storage || {};
	const pv = (st.pvs || [])[0] || null;
	const vg = (st.vgs || [])[0] || null;
	const pool = (st.thin_pools || [])[0] || null;
	const volumes = st.volumes || state.volumes || [];

	const pvTotal = (st.pvs || []).reduce((n, p) => n + (p.size_bytes || 0), 0) || null;
	const pvUsed = (st.pvs || []).reduce((n, p) => n + (p.used_bytes || 0), 0) || null;

	return {
		pv: pv && {
			name: (st.pvs || []).length > 1 ? `${st.pvs.length} PVs` : pv.name,
			total: pvTotal,
			used: pvUsed,
			frac: pvTotal ? pvUsed / pvTotal : null,
		},
		vg: vg && {
			name: vg.name,
			total: vg.size_bytes ?? null,
			used: vg.used_bytes ?? null,
			free: vg.free_bytes ?? null,
			frac: vg.size_bytes ? (vg.used_bytes || 0) / vg.size_bytes : null,
			lvCount: vg.lv_count ?? volumes.length,
			pvCount: vg.pv_count ?? (st.pvs || []).length,
		},
		pool: pool && {
			name: pool.name,
			total: pool.size_bytes ?? null,
			frac: pool.data_percent != null ? pool.data_percent / 100 : null,
			dataPercent: pool.data_percent ?? null,
			metaPercent: pool.metadata_percent ?? null,
			backing: pool.backing || null,
		},
		volumes,
	};
}

// Severity band from a fill fraction: hot ≥0.75, crit ≥0.90. Null → "ok".
function sev(fraction) {
	if (fraction == null) return "ok";
	if (fraction >= 0.9) return "crit";
	if (fraction >= 0.75) return "warn";
	return "ok";
}

// ── provisioningClass(vm) → shared | dedicated | null, from real cgroup caps ───
// The `provisioning` field is a controller fact the host never records (CONTRACT
// § not on the host). But the CPU class IS derivable from the cgroup the jailer
// wrote: `cpu.max` = "<quota> <period>", parsed server-side into `cpu_cap_cores`.
//   · cap == vcpus  → DEDICATED: the VM is hard-capped at its FULL paper allotment
//                     (quota = vcpus × period), so it can always use everything it
//                     was promised — no CPU overcommit.
//   · cap <  vcpus  → SHARED: capped BELOW its allotment, so its vcpus are
//                     overcommitted against the host and it bursts to the cap under
//                     contention — the reclaimable-overprovision class.
//   · cap missing / vcpus unknown (stopped VM: no cgroup; or cpu.max "max") →
//                     null: not classifiable from the host alone.
// An explicit `provisioning` field (mock, or a controller feed) always wins — the
// cgroup inference is the fallback for a real host that carries only caps.
export function provisioningClass(vm) {
	if (!vm) return null;
	if (vm.provisioning === "shared" || vm.provisioning === "dedicated") return vm.provisioning;
	const cap = vm.cpu_cap_cores;
	const vcpus = vm.vcpus;
	if (cap == null || vcpus == null || vcpus <= 0) return null;
	// A hair of float tolerance: quota/period division can leave 1.9999… for 2.
	if (cap >= vcpus - 1e-6) return "dedicated";
	return "shared";
}

// ── provisioning(state) → the fleet commit/use view (items 14/11) ─────────────
// The provisioning model (see the handoff §2), made legible in one panel:
//
//   · committed = Σ requests across running VMs (what we PROMISED customers)
//   · physical  = the host's real capacity (what we actually HAVE)
//   · used      = actual consumption right now (what customers ARE using)
//
// The two facts the operator must see: (a) overcommit is happening — committed
// past physical, factor = committed/physical; and (b) usage vs total — used well
// under physical means the overcommit bet is paying off. SHARED VMs are the
// overprovision (weight 25% floor, burst to their cap); DEDICATED are exact
// (weight 100%, no overcommit). We split committed by that axis so you can see
// how much of the promise is the reclaimable-under-contention shared kind.
//
// Disk is thin-pool: committed = Σ allocated (what customers see), used = Σ
// actually-written, physical = the pool size. Snapshots share extents so the
// pool's own fill can sit below Σ used — we report the pool fact as `used` when
// present, falling back to Σ disk_used_bytes.
export function provisioning(state) {
	const host = state.host || {};
	const vms = state.virtual_machines || [];
	const running = vms.filter((v) => v.state === "Running");
	const sum = (vs, fn) => vs.reduce((n, v) => n + (fn(v) || 0), 0);

	// Class from the explicit field OR, on a real host, inferred from the cgroup
	// cap (cap<vcpus ⇒ shared, cap==vcpus ⇒ dedicated). So the split is whole even
	// when the controller never tagged the VMs.
	const shared = running.filter((v) => provisioningClass(v) === "shared");
	const dedicated = running.filter((v) => provisioningClass(v) === "dedicated");

	// CPU — cores. request = cpu_request_cores (fall back to vcpus). used is the
	// VM's cpu_pct (a fraction of ONE core) × 1; summed it's cores-in-use.
	// `cpu_pct` needs two cgroup samples (CONTRACT § honest blanks); under the dev
	// SSH proxy's single-shot --collect it is null on EVERY VM. When nothing
	// reports a percentage, "used" is UNKNOWN, not zero — pass null so the bar
	// reads "— / N vCPU" (honest silence) instead of a false, empty "0 / N".
	const cpuReq = (v) => v.cpu_request_cores ?? v.vcpus ?? 0;
	const cpuMeasured = running.some((v) => v.cpu_pct != null);
	const cpuUsed = (v) => (v.cpu_pct != null ? v.cpu_pct / 100 : 0);
	const cpu = resource("CPU", {
		committed: sum(running, cpuReq),
		used: cpuMeasured ? sum(running, cpuUsed) : null,
		physical: host.cpu_total ?? null,
		unit: "vCPU",
		sharedCommitted: sum(shared, cpuReq),
		dedicatedCommitted: sum(dedicated, cpuReq),
		fmt: (n) => trim(n),
	});

	// Memory — MiB. cap == request (hard cap), so committed = Σ mem_request.
	const memReq = (v) => v.mem_request_mib ?? v.mem_mib ?? 0;
	const memUsed = (v) => v.mem_used_mib ?? 0;
	const mem = resource("Memory", {
		committed: sum(running, memReq),
		used: sum(running, memUsed),
		physical: host.mem_total_mib ?? null,
		unit: "G",
		sharedCommitted: sum(shared, memReq),
		dedicatedCommitted: sum(dedicated, memReq),
		fmt: (mib) => `${trim(mib / 1024)}G`,
	});

	// Disk — thin pool. committed = Σ allocated (all VMs, not just running: a
	// stopped VM still holds its extents). used prefers the real pool fill.
	const pool = state.pool || {};
	const poolTotalGib = parseLvSize(pool.size);
	const poolFrac = pool.data_percent != null ? pool.data_percent / 100 : null;
	const poolUsedGib = poolTotalGib != null && poolFrac != null ? poolTotalGib * poolFrac : null;
	// Allocated disk: the real collector emits the LV size as `disk_size_bytes`;
	// the mock carries `disk_allocated_bytes`. Prefer the real field, fall back to
	// the mock, so the bar is whole on both.
	const diskAllocGib = (v) => (v.disk_size_bytes ?? v.disk_allocated_bytes ?? 0) / GIB;
	const allocGib = sum(vms, diskAllocGib);
	const sumUsedGib = sum(vms, (v) => (v.disk_used_bytes || 0) / GIB);
	const disk = resource("Disk", {
		committed: allocGib,
		used: poolUsedGib != null ? poolUsedGib : sumUsedGib,
		physical: poolTotalGib,
		unit: "G",
		sharedCommitted: sum(
			vms.filter((v) => provisioningClass(v) === "shared"),
			diskAllocGib
		),
		dedicatedCommitted: sum(
			vms.filter((v) => provisioningClass(v) === "dedicated"),
			diskAllocGib
		),
		fmt: (n) => `${trim(n)}G`,
	});

	return {
		resources: [cpu, mem, disk],
		counts: { shared: shared.length, dedicated: dedicated.length, running: running.length },
	};
}

const GIB = 1024 * 1024 * 1024;

// One provisioning resource row. Carries the three magnitudes + the derived
// overcommit factor and the shared/dedicated commit split, plus a pre-formatted
// label for each. `overcommit` = committed/physical (>1 ⇒ we promised more than
// we have). `usedFrac`/`committedFrac` are fractions of physical for the bar.
function resource(label, o) {
	const { committed, used, physical, unit, sharedCommitted, dedicatedCommitted, fmt } = o;
	const has = physical != null && physical > 0;
	// `used` is null when the metric is unmeasured (e.g. CPU under the proxy). Keep
	// the usage fraction and severity null too — an unmeasured resource has no
	// pressure to report, and the bar renders empty rather than NaN-wide.
	const measured = has && used != null;
	return {
		label,
		unit,
		committed,
		used,
		physical,
		sharedCommitted,
		dedicatedCommitted,
		overcommit: has ? committed / physical : null,
		committedFrac: has ? committed / physical : null,
		usedFrac: measured ? used / physical : null,
		// Severity reads off how full the REAL capacity is (used/physical) — that's
		// the number that actually hurts, not the paper overcommit.
		severity: sev(measured ? used / physical : null),
		text: {
			committed: fmt(committed),
			used: fmt(used),
			physical: has ? fmt(physical) : null,
			shared: fmt(sharedCommitted),
			dedicated: fmt(dedicatedCommitted),
		},
	};
}

// A number trimmed to at most one decimal, dropping a trailing .0 (2.0→"2",
// 3.73→"3.7"). Keeps the aggregates tabular without noise.
function trim(n) {
	if (n == null || !Number.isFinite(n)) return "—";
	return (Math.round(n * 10) / 10).toString();
}

// ── perVmProvisioning(vm) → the Machines per-VM cells (item 14/11 columns) ─────
// Compact request→cap→used per resource for one VM. Shared shows its weight/burst
// story (a 25% floor that bursts to the cap); dedicated is exact. Used is the
// live sample. Returns pre-formatted strings so the table stays dumb.
export function perVmProvisioning(vm) {
	// The class: explicit field if present, else inferred from the cgroup cap so a
	// real host still shows shared/dedicated in the Prov column (see provisioningClass).
	const kind = provisioningClass(vm);
	const shared = kind === "shared";
	const req = vm.cpu_request_cores ?? vm.vcpus ?? null;
	const cap = vm.cpu_cap_cores ?? req;
	const cpuUsed = vm.cpu_pct != null ? vm.cpu_pct / 100 : null;
	const memReq = vm.mem_request_mib ?? vm.mem_mib ?? null;
	const memUsed = vm.mem_used_mib ?? null;
	return {
		kind, // "shared" | "dedicated" | null
		shared,
		// CPU: the request/cap in cores. The shared-vs-dedicated (burst-vs-exact)
		// story is carried by the Prov column, so the number stays bare here.
		cpu: req == null ? "" : `${trim(req)}`,
		cpuReq: req,
		cpuCap: cap,
		cpuUsed,
		cpuUsedText: cpuUsed == null ? "" : `${trim(cpuUsed)}`,
		// Memory: cap == request, so one number. Request in G; used in G too so the
		// pair shares a unit and stays narrow (0.3G, not 342M).
		mem: memReq == null ? "" : `${trim(memReq / 1024)}G`,
		memReq,
		memUsed,
		memUsedText: memUsed == null ? "" : `${trim(memUsed / 1024)}G`,
		memUsedFrac: memReq ? (memUsed || 0) / memReq : null,
	};
}

// ── alerts(state) → the stateful alert list ──────────────────────────────────
// Each alert: { key, severity, title, detail, since, vm?, jump? }. `key` is
// stable (survives refreshes so a UI could diff fire/clear once history exists).
// `jump` names a pre-filter the Alerts/Overview surfaces can apply to Machines.
// `since` is the truest timestamp we can attach (the host read time) — we do NOT
// invent a fire-time we can't observe.
export function alerts(state) {
	const out = [];
	const since = state.host?.collected_at || null;
	const vms = state.virtual_machines || [];
	const q = quotas(state);

	// Resource pressure — one alert per bar over threshold.
	for (const b of q) {
		if (b.severity === "ok") continue;
		out.push({
			key: `pressure:${b.label.toLowerCase()}`,
			severity: b.severity === "crit" ? "crit" : "warn",
			title: `${b.label} pressure`,
			detail: pressureDetail(b),
			since,
			jump: null,
		});
	}

	// Failed VMs — a unit that died is the clearest "wants a look".
	for (const vm of vms.filter((v) => v.state === "Failed")) {
		out.push({
			key: `failed:${vm.uuid}`,
			severity: "crit",
			title: "VM failed",
			detail: `${uuid8(vm.uuid)} — its unit is inactive; start or terminate it.`,
			since,
			vm: vm.uuid,
			jump: "state:failed",
		});
	}

	// Disk-hot VMs — a THIN VM disk growing toward full (≥85%; ≥95% crit). The
	// signal is thin-pool `data_percent`, which only means "filling" for a thin
	// volume that still has room to grow. A fully-allocated (thick) LV — a plain
	// bench/image clone with no snapshot origin — reports data_percent=100 with
	// used==size *structurally*, forever; that is not filling. Real hosts run a
	// mix of both (thick bench images sit permanently at 100%), so gate on
	// used<size: only a volume with remaining headroom can be "filling". Without
	// used/size (a sparse capture) fall back to the bare percent.
	for (const vm of vms) {
		const pct = vm.disk_data_percent;
		if (pct == null || pct < 85) continue;
		const size = vm.disk_size_bytes;
		const used = vm.disk_used_bytes;
		if (size != null && used != null && used >= size) continue; // thick/at-rest, not filling
		out.push({
			key: `disk:${vm.uuid}`,
			severity: pct >= 95 ? "crit" : "warn",
			title: "VM disk filling",
			detail: `${uuid8(vm.uuid)} — disk ${pct}% full.`,
			since,
			vm: vm.uuid,
			jump: "disk:hot",
		});
	}

	// Idle-but-reserved — a stopped/paused VM still holds vCPU/RAM: reclaimable.
	for (const vm of vms) {
		if (vm.state !== "Stopped" && vm.state !== "Paused") continue;
		if (!vm.vcpus && !vm.mem_mib) continue;
		out.push({
			key: `idle:${vm.uuid}`,
			severity: "warn",
			title: "Idle VM holds capacity",
			detail: `${uuid8(vm.uuid)} — ${vm.state.toLowerCase()} but holds ${
				vm.vcpus ?? "?"
			} vCPU · ${vm.mem_mib != null ? fmtMib(vm.mem_mib) : "?"}. Terminate to reclaim.`,
			since,
			vm: vm.uuid,
			jump: "state:idle",
		});
	}

	// Crit first, then warn; stable order within a band by key.
	out.sort((a, b) => rank(a.severity) - rank(b.severity) || a.key.localeCompare(b.key));
	return { firing: out, cleared: [] }; // cleared: none until backend carries history
}

function pressureDetail(b) {
	if (b.label === "Pool") return `thin pool ${b.used}% full.`;
	const pct = b.fraction != null ? Math.round(b.fraction * 100) : "?";
	// Memory is carried in MiB internally but always READS in the shared G/T unit
	// family (unit audit — no MiB in the UI). vCPU stays a bare count.
	if (b.label === "Memory") {
		const committed = fmtMib(b.used + b.idle);
		const budget = b.budget != null ? fmtMib(b.budget) : "?";
		return `${committed} of ${budget} committed (${pct}% of budget).`;
	}
	return `${b.used + b.idle} of ${b.budget ?? "?"} vCPU committed (${pct}% of budget).`;
}

function rank(sev) {
	return sev === "crit" ? 0 : sev === "warn" ? 1 : 2;
}

// ── alertGroups(state) → the glanceable summary (Overview landing) ───────────
// At scale the firing list is hundreds long; the Overview card must NOT
// enumerate it (EXPLORATION: anomalies are "tens, not thousands"). This folds
// firing alerts into one line per KIND — count, worst severity, a jump — so the
// landing stays constant-size at any VM count. The Alerts page still lists all.
export function alertGroups(state) {
	const { firing } = alerts(state);
	const by = new Map();
	for (const a of firing) {
		const kind = a.key.split(":")[0]; // pressure | failed | disk | idle
		const g = by.get(kind) || { kind, count: 0, severity: "warn", jump: a.jump, example: a };
		g.count++;
		if (a.severity === "crit") g.severity = "crit";
		by.set(kind, g);
	}
	const label = {
		pressure: "resource pressure",
		failed: "failed",
		disk: "disk filling",
		idle: "idle but holding capacity",
	};
	const groups = [...by.values()].map((g) => ({
		key: g.kind,
		severity: g.severity,
		count: g.count,
		jump: g.jump,
		title: `${g.count} ${g.count === 1 ? "machine" : "machines"} · ${label[g.kind] || g.kind}`,
		// When a group has exactly one member, carry its VM so the line can jump
		// straight to it; otherwise the jump is the facet filter.
		vm: g.count === 1 ? g.example.vm : null,
		detail: g.count === 1 ? g.example.detail : null,
	}));
	groups.sort((a, b) => rank(a.severity) - rank(b.severity) || b.count - a.count);
	return groups;
}

// ── inventory(state) → the Overview census line ──────────────────────────────
// One glanceable line of "what's on this host": the fleet (running / total, plus
// a migrating tail only when something is in flight) followed by the object
// stores — volumes, snapshots, images, reserved IPs. Each item carries a `jump`
// { domain, table } so the noun cross-links to its own rail page, matching how
// the alert lines jump. HONEST: a zero-migrating fleet drops the clause rather
// than printing "0 migrating" (same suppression the alerts use). Nouns pluralise
// by count. Returns { machines: {running, total, migrating, jump}, stores:[...] }.
export function inventory(state) {
	const vms = state.virtual_machines || [];
	const running = vms.filter((v) => v.state === "Running").length;
	const migrating = vms.filter((v) => vmMigrating(state, v)).length;

	const store = (count, singular, jump) => ({
		count,
		label: count === 1 ? singular : `${singular}s`,
		jump,
	});

	return {
		machines: {
			running,
			total: vms.length,
			migrating, // caller shows the clause only when > 0
			jump: { domain: "machines", table: "machines" },
		},
		stores: [
			store((state.volumes || []).length, "volume", { domain: "storage", table: "volumes" }),
			store((state.snapshots || []).length, "snapshot", {
				domain: "images",
				table: "snapshots",
			}),
			store((state.images || []).length, "image", { domain: "images", table: "images" }),
			store((state.reserved_ips || []).length, "reserved IP", {
				domain: "network",
				table: "reserved",
			}),
		],
	};
}

// A compact count for the header badge: { crit, warn }.
export function alertCounts(state) {
	const { firing } = alerts(state);
	return {
		crit: firing.filter((a) => a.severity === "crit").length,
		warn: firing.filter((a) => a.severity === "warn").length,
	};
}

// ── events(state) → one chronological log ────────────────────────────────────
// VM lifecycle + snapshots + migrations + alert transitions, folded into one
// stream. Derived from the current snapshot (units carry the lifecycle facts,
// migrations the in-flight ones, tasks the recent host actions). Honest: without
// a persisted journal these are the events OBSERVABLE now, timestamped by the
// read; the tasks section, when present, carries real start times.
export function events(state) {
	const out = [];
	const at = state.host?.collected_at || null;

	for (const t of state.tasks || []) {
		out.push({
			key: `task:${t.id}`,
			at: t.started_at || at,
			kind: "task",
			text: `${t.name} — ${t.status}${t.duration ? " · " + t.duration : ""}`,
		});
	}
	for (const m of state.migrations || []) {
		out.push({
			key: `mig:${m.unit}`,
			at,
			kind: "migration",
			text: `migration ${m.state}${m.peer ? " ↔ " + m.peer : ""}`,
		});
	}
	for (const vm of (state.virtual_machines || []).filter((v) => v.state === "Failed")) {
		out.push({ key: `fail:${vm.uuid}`, at, kind: "vm", text: `${uuid8(vm.uuid)} failed` });
	}

	// Newest first when timestamps are comparable; stable otherwise.
	out.sort((a, b) => String(b.at || "").localeCompare(String(a.at || "")));
	return out;
}

// ── Shared view helpers ──────────────────────────────────────────────────────
// An ISO timestamp rendered as the dashboard's plain "YYYY-MM-DD HH:MM:SS" form.
// `utc` keeps the trailing " UTC" (alerts/footer want it; the events log doesn't).
export function shortTime(iso, { utc = false } = {}) {
	if (!iso) return "—";
	// Compact: "YYYY-MM-DD HH:MM" — drop seconds and the " UTC" suffix (the footer
	// already states the collection is UTC), so the When/Time column stays narrow
	// and the list never needs a horizontal scroll at scale.
	const s = String(iso).replace("T", " ").replace("Z", "");
	const m = s.match(/^(\d{4}-\d{2}-\d{2}[ ]\d{2}:\d{2})/);
	return m ? m[1] : s;
}
// The severity glyph: crit = filled, warn = half. Contrast, not colour.
export function sevTick(sev) {
	return sev === "crit" ? "●" : "◐";
}

// Scale a numeric series to [x, y] pixel points inside a w×h box (y grows down),
// dropping non-numbers. `padY` insets the top/bottom so the trace doesn't touch
// the edges. Shared by the Sparkline and the AreaChart — the only shape both
// need. A single point centres on x (no fabricated trend); empty → [].
export function scaleSeries(values, w, h, padY = 2) {
	const v = (values || []).filter((n) => typeof n === "number" && !Number.isNaN(n));
	if (!v.length) return [];
	const min = Math.min(...v);
	const max = Math.max(...v);
	const span = max - min || 1;
	return v.map((n, i) => [
		v.length > 1 ? (i / (v.length - 1)) * w : w / 2,
		padY + (1 - (n - min) / span) * (h - 2 * padY),
	]);
}

// ── parseNftRule(rule) → structured columns (item 15) ────────────────────────
// The raw nft rule string ("ip6 saddr 2001:… iifname \"atlas-h0cc727b\" accept",
// "ip daddr 51.159.76.127 dnat ip to 100.64.0.14") reads like a config dump. We
// split it into the columns an operator actually scans:
//
//   · verdict — the terminal action (accept · drop · dnat · snat · masquerade)
//   · match   — the packet selector, direction-aware ("→ <daddr>" dest,
//               "<saddr> →" source), the part that says WHICH packets
//   · iface   — the bound interface (in "iif eth0" / out "oif atlas-h…")
//   · to      — the rewrite target for dnat/snat (the "to X" tail)
//
// Pure string parsing, no backend change. Unknown shapes fall back to the raw
// text in `match` so nothing is ever hidden — you always see the whole rule.
const NFT_VERDICTS = [
	"accept",
	"drop",
	"reject",
	"masquerade",
	"dnat",
	"snat",
	"return",
	"jump",
	"goto",
];

export function parseNftRule(rule) {
	const raw = String(rule || "").trim();
	const out = { verdict: "", match: raw, iface: "", to: "", raw };
	if (!raw) return out;

	let s = raw;

	// Interface: iifname/oifname "<dev>" (or bare iif/oif). Prefix ↓ in / ↑ out.
	const ifm = s.match(/\b(o|i)if(?:name)?\s+"?([\w.@-]+)"?/);
	if (ifm) {
		out.iface = `${ifm[1] === "i" ? "in" : "out"} ${ifm[2]}`;
		s = s.replace(ifm[0], " ");
	}

	// Rewrite target: "dnat ip to X" / "snat ip to X" — pull the address after "to".
	const nat = s.match(/\b(dnat|snat)\b(?:\s+ip6?)?\s+to\s+([\w:.\/\[\]]+)/);
	if (nat) {
		out.verdict = nat[1];
		out.to = nat[2];
		s = s.replace(nat[0], " ");
	}

	// Terminal verdict word (if not already a nat rewrite).
	if (!out.verdict) {
		const v = s.match(new RegExp(`\\b(${NFT_VERDICTS.join("|")})\\b`));
		if (v) {
			out.verdict = v[1];
			s = s.replace(v[0], " ");
		}
	}

	// Match: a direction-aware selector. saddr = source, daddr = dest.
	const sad = s.match(/\bip6?\s+saddr\s+([\w:.\/\[\]]+)/);
	const dad = s.match(/\bip6?\s+daddr\s+([\w:.\/\[\]]+)/);
	if (sad && dad) out.match = `${sad[1]} → ${dad[1]}`;
	else if (dad) out.match = `→ ${dad[1]}`;
	else if (sad) out.match = `${sad[1]} →`;
	else {
		// Not an addr rule — keep whatever selector remains (ports, ct state…),
		// trimmed of the verdict/iface we already lifted out.
		const rest = s.replace(/\s+/g, " ").trim();
		out.match = rest || raw;
	}
	return out;
}

// Exposed for tests / reuse.
export { nftRecords, vmTokens, uuid8 };
