package network

import (
	"strings"
	"testing"

	"github.com/frappe/atlas/metal/internal/vm"
)

func TestDisabledFirewallAcceptsForwardedTraffic(t *testing.T) {
	table, err := renderFirewallTable(vm.FirewallConfiguration{}, false)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(table, ":FORWARD ACCEPT [0:0]") {
		t.Fatalf("table =\n%s", table)
	}
	if strings.Contains(table, "-A FORWARD") {
		t.Fatalf("disabled firewall contains rules:\n%s", table)
	}
}

func TestFirewallRendersRulesForEachAddressFamily(t *testing.T) {
	configuration := vm.FirewallConfiguration{
		Enabled: true,
		Inbound: []vm.FirewallRule{{
			Protocol: vm.FirewallProtocolTCP,
			Ports:    "8000-9000",
			CIDRs:    []string{"203.0.113.0/24", "2001:db8::/32"},
		}},
		Outbound: []vm.FirewallRule{{
			Protocol: vm.FirewallProtocolICMP,
			CIDRs:    []string{"0.0.0.0/0", "::/0"},
		}},
	}

	ipv4, err := renderFirewallTable(configuration, false)
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		":FORWARD DROP [0:0]",
		"--ctstate RELATED,ESTABLISHED",
		"-s 203.0.113.0/24 -o tap0 -p tcp -m tcp --dport 8000:9000 -j ACCEPT",
		"-d 0.0.0.0/0 -i tap0 -p icmp -j ACCEPT",
	} {
		if !strings.Contains(ipv4, expected) {
			t.Errorf("IPv4 table does not contain %q:\n%s", expected, ipv4)
		}
	}
	if strings.Contains(ipv4, "2001:db8") || strings.Contains(ipv4, "::/0") {
		t.Fatalf("IPv4 table contains IPv6 rules:\n%s", ipv4)
	}

	ipv6, err := renderFirewallTable(configuration, true)
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"-s 2001:db8::/32 -o tap0 -p tcp -m tcp --dport 8000:9000 -j ACCEPT",
		"-d ::/0 -i tap0 -p ipv6-icmp -j ACCEPT",
	} {
		if !strings.Contains(ipv6, expected) {
			t.Errorf("IPv6 table does not contain %q:\n%s", expected, ipv6)
		}
	}
}

func TestFirewallTableComparisonIgnoresSaveComments(t *testing.T) {
	desired := "*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n"
	current := "# Generated by iptables-save\n*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n# Completed\n"

	if normalizeFirewallTable(current) != normalizeFirewallTable(desired) {
		t.Fatal("save comments changed the table comparison")
	}
}
