#!/bin/bash
# Phase 5 e2e: SSH into a provisioned VM over its public IPv6 and assert the
# fit-and-finish guarantees from [llm/plan/real-vm-fitfinish.md]. Probes the
# *observable* outcomes the plan promises:
#
#   - per-VM hostname `atlas-<first-8-of-uuid>`
#   - per-VM `/etc/machine-id` (non-empty, regenerated by systemd)
#   - per-VM ssh host keys (regenerated on first boot)
#   - no leftover fcnet IPv4
#   - /etc/hosts cleaned (no Docker bridge entry; 127.0.1.1 line present)
#   - root password locked, sshd password-auth off
#   - /swapfile mounted as swap
#
# Inputs:
#   VIRTUAL_MACHINE_NAME  - UUID; first 8 chars must match the hostname.
#   VIRTUAL_MACHINE_IPV6  - destination address for the SSH probe.
#   SSH_PRIVATE_KEY       - private half of the key Atlas injected.

set -euo pipefail
# Disable bash -x tracing for the rest of the script: the SSH_PRIVATE_KEY
# env var is in scope and any `${SSH_PRIVATE_KEY}` expansion (including the
# `:?` parameter check below) would trace the key value into stderr, which
# we capture into the Task row.
{ set +x; } 2>/dev/null

: "${VIRTUAL_MACHINE_NAME:?}"
: "${VIRTUAL_MACHINE_IPV6:?}"
: "${SSH_PRIVATE_KEY:?}"

key_file="$(mktemp /tmp/atlas-guest-probe-XXXXXX.key)"
trap 'rm -f "$key_file"' EXIT
printf '%s\n' "$SSH_PRIVATE_KEY" >"$key_file"
chmod 0600 "$key_file"

# Wait for sshd in the guest. The systemd unit is up within a couple of
# seconds, but ssh-keygen -A on first boot can add a few more.
deadline=$((SECONDS + 90))
while ! ssh \
        -i "$key_file" \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o BatchMode=yes \
        -o ConnectTimeout=5 \
        "root@${VIRTUAL_MACHINE_IPV6}" true 2>/dev/null; do
    if [ "$SECONDS" -ge "$deadline" ]; then
        echo "guest ssh not ready after 90s at ${VIRTUAL_MACHINE_IPV6}" >&2
        exit 1
    fi
    sleep 3
done

guest() {
    ssh \
        -i "$key_file" \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o BatchMode=yes \
        -o ConnectTimeout=10 \
        "root@${VIRTUAL_MACHINE_IPV6}" "$@"
}

expected_hostname="atlas-${VIRTUAL_MACHINE_NAME:0:8}"

# Run the assertions inside a single SSH session so we get one round trip and
# one clean failure point.
guest bash -s "$expected_hostname" <<'REMOTE'
set -euo pipefail
expected_hostname="$1"

fail() {
    echo "FAIL: $*" >&2
    exit 1
}

# 1. Hostname.
actual_hostname="$(hostname)"
[ "$actual_hostname" = "$expected_hostname" ] \
    || fail "hostname=${actual_hostname} want=${expected_hostname}"

# 2. /etc/hostname matches.
[ "$(cat /etc/hostname)" = "$expected_hostname" ] \
    || fail "/etc/hostname mismatch"

# 3. /etc/hosts has the 127.0.1.1 line and no Docker bridge leftover.
grep -qE "^127\.0\.1\.1[[:space:]]+${expected_hostname}\$" /etc/hosts \
    || fail "/etc/hosts missing 127.0.1.1 ${expected_hostname}"
grep -qE "^172\.18\." /etc/hosts \
    && fail "/etc/hosts still has Docker bridge entry"

# 4. machine-id non-empty and not the well-known leaked one.
machine_id="$(cat /etc/machine-id)"
[ -n "$machine_id" ] || fail "/etc/machine-id is empty"
[ "$machine_id" != "4833ad8775a24dcc9d4b159af4e84d08" ] \
    || fail "/etc/machine-id is the leaked CI value"

# 5. SSH host key was regenerated (comment must not be the CI build host).
if [ -f /etc/ssh/ssh_host_ed25519_key.pub ]; then
    grep -q "root@bf0feaa40806" /etc/ssh/ssh_host_ed25519_key.pub \
        && fail "ssh host key still has CI build-container comment"
fi

# 6. fcnet artifacts gone.
[ -e /etc/systemd/system/fcnet.service ] \
    && fail "/etc/systemd/system/fcnet.service still present"
[ -e /usr/local/bin/fcnet-setup.sh ] \
    && fail "/usr/local/bin/fcnet-setup.sh still present"

# 7. eth0's only global IPv4 is the Atlas NAT44 egress address (100.64.x.x).
#    fcnet would have injected a 91.83.x.x/30; any non-100.64 global v4 is a
#    leftover and fails. (The 100.64 link is asserted in phase5-ipv4-egress.sh.)
ipv4="$(ip -4 -o addr show dev eth0 scope global 2>/dev/null | awk '{print $4}' || true)"
for cidr in $ipv4; do
    case "$cidr" in
        100.64.*) : ;;
        *) fail "eth0 has unexpected non-egress IPv4: $cidr" ;;
    esac
done

# 8. Root password locked.
shadow="$(grep '^root:' /etc/shadow)"
case "$shadow" in
    root:!:*|root:\*:*) : ;;
    *) fail "root shadow entry not locked: $shadow" ;;
esac

# 9. sshd password auth off. sshd -T output is lowercase keys, value as-is.
#    Use awk to extract the global setting tolerantly (whitespace, CR/LF).
pwauth="$(sshd -T 2>/dev/null \
    | awk 'tolower($1)=="passwordauthentication"{print tolower($2); exit}' \
    | tr -d '\r')"
[ "$pwauth" = "no" ] \
    || fail "sshd PasswordAuthentication is '$pwauth', want 'no'"

# 10. Swap on /swapfile.
swapon --show=NAME --noheadings | grep -qx /swapfile \
    || fail "swap on /swapfile not active"

# 11. This is the Ubuntu cloud image (the source we cut over to).
grep -q 'VERSION_ID="24.04"' /etc/os-release \
    || fail "/etc/os-release is not Ubuntu 24.04"

# 12. cloud-init is neutralized (sync-image.sh masks it). If it were live it
#     would race Atlas's mount-time identity injection. A masked unit reports
#     as 'masked'; reaching this prompt at all already proves the boot-blocking
#     waits (networkd-wait-online, snapd.seeded) are not hanging.
ci_state="$(systemctl is-enabled cloud-init.service 2>/dev/null || true)"
case "$ci_state" in
    masked|disabled|"") : ;;
    *) fail "cloud-init.service is '${ci_state}', want masked/disabled" ;;
esac

# 13. systemd-networkd-wait-online masked (Phase 0 caught it hanging boot).
wait_state="$(systemctl is-enabled systemd-networkd-wait-online.service 2>/dev/null || true)"
case "$wait_state" in
    masked|disabled|"") : ;;
    *) fail "systemd-networkd-wait-online is '${wait_state}', want masked" ;;
esac

echo "OK ${expected_hostname}"
REMOTE
